// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAEnQrg9YL1hZGWjwv_JWWyarWz_t3z38',
    appId: '1:896843697624:web:b47239c33eddef31e4f6ad',
    messagingSenderId: '896843697624',
    projectId: 'devmob-supportclient-8a095',
    authDomain: 'devmob-supportclient-8a095.firebaseapp.com',
    storageBucket: 'devmob-supportclient-8a095.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4E27CUxXkeA7xDYw57WpS7ShtwmfEoLM',
    appId: '1:896843697624:android:d2b0e4dd3876e11fe4f6ad',
    messagingSenderId: '896843697624',
    projectId: 'devmob-supportclient-8a095',
    storageBucket: 'devmob-supportclient-8a095.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvNNE0nGCRr168sQ1yRMLBMn37caRGHdY',
    appId: '1:896843697624:ios:8a9e8301f93c5e35e4f6ad',
    messagingSenderId: '896843697624',
    projectId: 'devmob-supportclient-8a095',
    storageBucket: 'devmob-supportclient-8a095.firebasestorage.app',
    iosBundleId: 'com.example.devmobSupportclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvNNE0nGCRr168sQ1yRMLBMn37caRGHdY',
    appId: '1:896843697624:ios:8a9e8301f93c5e35e4f6ad',
    messagingSenderId: '896843697624',
    projectId: 'devmob-supportclient-8a095',
    storageBucket: 'devmob-supportclient-8a095.firebasestorage.app',
    iosBundleId: 'com.example.devmobSupportclient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAEnQrg9YL1hZGWjwv_JWWyarWz_t3z38',
    appId: '1:896843697624:web:365402870ff95c39e4f6ad',
    messagingSenderId: '896843697624',
    projectId: 'devmob-supportclient-8a095',
    authDomain: 'devmob-supportclient-8a095.firebaseapp.com',
    storageBucket: 'devmob-supportclient-8a095.firebasestorage.app',
  );
}
